// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8OOTqmRYCx9S0Q9sxhBtipDJYkeU34iA',
    appId: '1:65764612150:web:253e20a69cfab3b4bfe097',
    messagingSenderId: '65764612150',
    projectId: 'traveler-food',
    authDomain: 'traveler-food.firebaseapp.com',
    databaseURL: 'https://traveler-food-default-rtdb.firebaseio.com',
    storageBucket: 'traveler-food.appspot.com',
    measurementId: 'G-3G7CPLHBGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDktlHOKgklqqMdnrxj6r4BHk9kvjElECI',
    appId: '1:65764612150:android:972cb4feddc63f93bfe097',
    messagingSenderId: '65764612150',
    projectId: 'traveler-food',
    databaseURL: 'https://traveler-food-default-rtdb.firebaseio.com',
    storageBucket: 'traveler-food.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeCEaL7PyTWaoDrvyzBp42d1pLOwvLwS8',
    appId: '1:65764612150:ios:119c58a99d734e89bfe097',
    messagingSenderId: '65764612150',
    projectId: 'traveler-food',
    databaseURL: 'https://traveler-food-default-rtdb.firebaseio.com',
    storageBucket: 'traveler-food.appspot.com',
    iosClientId: '65764612150-1fpui38csl272ama4tfjd1p7bjb3rhnh.apps.googleusercontent.com',
    iosBundleId: 'com.example.delivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeCEaL7PyTWaoDrvyzBp42d1pLOwvLwS8',
    appId: '1:65764612150:ios:1b7fff6478e5788abfe097',
    messagingSenderId: '65764612150',
    projectId: 'traveler-food',
    databaseURL: 'https://traveler-food-default-rtdb.firebaseio.com',
    storageBucket: 'traveler-food.appspot.com',
    iosClientId: '65764612150-hr0rduj3jl30ph74cih7vnbop0bf0gta.apps.googleusercontent.com',
    iosBundleId: 'com.example.delivery.RunnerTests',
  );
}
